preamble = ""
url = "https://gitlab.com/project-or-group-name"
token = "..."
milestones = ["milestone-name"]
parameters = [
    ["state", "closed"],
    ["include_subgroups", "true"]
]
closing_remarks = ""
output = "output.adoc"
